<a href="https://colab.research.google.com/github/Missboonyos/BC12_Intro_to_Pandas/blob/main/Intro_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Pandas**

In [ ]:
import pandas as pd

In [ ]:
# Create dataframe from scratch
raw_data = {
    "name": ["Jan", "Febby", "Marchy", "Abril", "May"],
    "age" : [20, 21, 19, 18, 23],
    "gender": ["M", "F", "M", "F", "M"]
}

df = pd.DataFrame(raw_data) # to reuse the result

In [ ]:
df

     name  age gender
0     Jan   20      M
1   Febby   21      F
2  Marchy   19      M
3   Abril   18      F
4     May   23      M

In [ ]:
# Add new column
df['city'] = ["Prague", "London", "Frankfurt", "Berlin", "Bangkok"]

In [ ]:
# Check Shape
df.shape

(5, 4)

In [ ]:
df

     name  age gender       city
0     Jan   20      M     Prague
1   Febby   21      F     London
2  Marchy   19      M  Frankfurt
3   Abril   18      F     Berlin
4     May   23      M    Bangkok

In [ ]:
# drop city
df = df.drop("city", axis=1)

In [ ]:
df

     name  age gender
0     Jan   20      M
1   Febby   21      F
2  Marchy   19      M
3   Abril   18      F
4     May   23      M

In [ ]:
# remove index = 2
df = df.drop(2, axis=0)

In [ ]:
df

    name  age gender
0    Jan   20      M
1  Febby   21      F
3  Abril   18      F
4    May   23      M

In [ ]:
df.reset_index(drop=True)

    name  age gender
0    Jan   20      M
1  Febby   21      F
2  Abril   18      F
3    May   23      M

In [ ]:
df

    name  age gender
0    Jan   20      M
1  Febby   21      F
3  Abril   18      F
4    May   23      M

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df

    name  age gender
0    Jan   20      M
1  Febby   21      F
2  Abril   18      F
3    May   23      M

In [ ]:
# column renames
df.columns

Index(['name', 'age', 'gender'], dtype='object')

In [ ]:
# Convert df.columns to a list
list(df.columns)

['name', 'age', 'gender']

In [ ]:
# rename columns
df.columns = ['nickname', 'age', 'sex']
df

  nickname  age sex
0      Jan   20   M
1    Febby   21   F
2    Abril   18   F
3      May   23   M

In [ ]:
df['nickname']

0      Jan
1    Febby
2    Abril
3      May
Name: nickname, dtype: object

In [ ]:
type(df['nickname'])

pandas.core.series.Series

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
# create a new series
s1 = pd.Series(['Mary', 20, 'F'], index=['nickname', 'age', 'sex'])
print(s1)
print(type(s1))

nickname    Mary
age           20
sex            F
dtype: object
<class 'pandas.core.series.Series'>

In [ ]:
# append s1 to df # Append using concat (modern Pandas)
df = pd.concat([df, s1.to_frame().T], ignore_index=True)
df

  nickname age sex
0      Jan  20   M
1    Febby  21   F
2    Abril  18   F
3      May  23   M
4     Mary  20   F

In [ ]:
df['age'] = df['age'].astype(int)

In [ ]:
df['age']

0    20
1    21
2    18
3    23
4    20
Name: age, dtype: int64

In [ ]:
# create a new column
s2 = pd.Series(['London', 'New York', 'Berlin', 'Madrid', 'Surin'])
df['city'] = s2
df

  nickname  age sex      city
0      Jan   20   M    London
1    Febby   21   F  New York
2    Abril   18   F    Berlin
3      May   23   M    Madrid
4     Mary   20   F     Surin

In [ ]:
# write csv file
df.to_csv('new_df.csv')

In [ ]:
# import excel file
df3 = pd.read_excel('/content/Logistic Regression Workbook_MyPractice.xlsx')
df3

   Lesson                           Content
0       1  When to use Logistic Regression?
1       2                     A little math
2       3                    Model training
3       4                  Model evaluation

In [ ]:
# import csv file
df4 = pd.read_json('/content/sample_data/anscombe.json')
df4

   Series   X      Y
0       I  10   8.04
1       I   8   6.95
2       I  13   7.58
3       I   9   8.81
4       I  11   8.33
5       I  14   9.96
6       I   6   7.24
7       I   4   4.26
8       I  12  10.84
9       I   7   4.81
10      I   5   5.68
11     II  10   9.14
12     II   8   8.14
13     II  13   8.74
14     II   9   8.77
15     II  11   9.26
16     II  14   8.10
17     II   6   6.13
18     II   4   3.10
19     II  12   9.13
20     II   7   7.26
21     II   5   4.74
22    III  10   7.46
23    III   8   6.77
24    III  13  12.74
25    III   9   7.11
26    III  11   7.81
27    III  14   8.84
28    III   6   6.08
29    III   4   5.39
30    III  12   8.15
31    III   7   6.42
32    III   5   5.73
33     IV   8   6.58
34     IV   8   5.76
35     IV   8   7.71
36     IV   8   8.84
37     IV   8   8.47
38     IV   8   7.04
39     IV   8   5.25
40     IV  19  12.50
41     IV   8   5.56
42     IV   8   7.91
43     IV   8   6.89